"""
PhantomEye — Reporter
Saves OSINT results to JSON and HTML reports.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from rich.console import Console

from ..config import Config

console = Console()


class Reporter:
    def __init__(self, session_id: int, target: str, target_type: str):
        cfg = Config.load()
        self.reports_dir = Path(cfg.reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)
        self.session_id = session_id
        self.target = target
        self.target_type = target_type
        self.timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        self.safe_target = "".join(c for c in target if c.isalnum() or c in "._-")

    def _base_filename(self) -> str:
        return f"phantomeye_{self.target_type}_{self.safe_target}_{self.timestamp}"

    def _save_json(self, data: dict, ai_summary: Optional[str]) -> Path:
        payload = {
            "meta": {
                "tool":        "PhantomEye",
                "version":     "1.0.0",
                "target_type": self.target_type,
                "target":      self.target,
                "timestamp":   self.timestamp,
                "session_id":  self.session_id,
            },
            "results":    data,
            "ai_analysis": ai_summary,
        }
        path = self.reports_dir / f"{self._base_filename()}.json"
        with open(path, "w") as f:
            json.dump(payload, f, indent=2, default=str)
        return path

    def _save_html(self, data: dict, ai_summary: Optional[str]) -> Path:
        data_json = json.dumps(data, indent=2, default=str)
        ai_html = (
            ai_summary.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                       .replace("\n", "<br>")
            if ai_summary else "<em>AI analysis not available.</em>"
        )

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PhantomEye Report — {self.target}</title>
  <style>
    :root {{
      --bg: #0d1117; --surface: #161b22; --border: #30363d;
      --accent: #00d4ff; --accent2: #9f67ff; --text: #e6edf3;
      --text-muted: #7d8590; --success: #3fb950; --danger: #f85149;
      --warning: #d29922; --font: "Fira Code", "Cascadia Code", monospace;
    }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ background: var(--bg); color: var(--text); font-family: var(--font); padding: 2rem; line-height: 1.6; }}
    header {{ border-bottom: 1px solid var(--border); padding-bottom: 1.5rem; margin-bottom: 2rem; }}
    .logo {{ font-size: 1.8rem; font-weight: 700; color: var(--accent); letter-spacing: 2px; }}
    .meta {{ color: var(--text-muted); font-size: 0.85rem; margin-top: 0.5rem; }}
    .meta span {{ color: var(--accent2); }}
    section {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px;
               padding: 1.5rem; margin-bottom: 1.5rem; }}
    h2 {{ font-size: 1rem; color: var(--accent); letter-spacing: 1px; margin-bottom: 1rem;
          text-transform: uppercase; }}
    .ai-analysis {{ white-space: pre-wrap; font-family: sans-serif; font-size: 0.95rem;
                    line-height: 1.7; color: var(--text); }}
    pre {{ background: var(--bg); border: 1px solid var(--border); border-radius: 4px;
           padding: 1rem; overflow-x: auto; font-size: 0.82rem; color: #79c0ff; }}
    footer {{ text-align: center; color: var(--text-muted); font-size: 0.8rem; margin-top: 2rem; }}
    .badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px;
              font-size: 0.75rem; font-weight: 600; margin: 0.2rem; }}
    .badge-cyan {{ background: rgba(0,212,255,0.15); color: var(--accent); border: 1px solid var(--accent); }}
  </style>
</head>
<body>
  <header>
    <div class="logo">👁 PHANTOMEYE</div>
    <div class="meta">
      Target: <span>{self.target}</span> &nbsp;|&nbsp;
      Type: <span>{self.target_type}</span> &nbsp;|&nbsp;
      Session: <span>{self.session_id}</span> &nbsp;|&nbsp;
      Generated: <span>{self.timestamp}</span>
    </div>
  </header>

  <section>
    <h2>🤖 AI Intelligence Analysis</h2>
    <div class="ai-analysis">{ai_html}</div>
  </section>

  <section>
    <h2>📦 Raw OSINT Data</h2>
    <pre id="raw-data">{data_json}</pre>
  </section>

  <footer>
    <p>Generated by PhantomEye v1.0.0 — AI-Powered OSINT Framework</p>
    <p style="margin-top:0.5rem; color:#f85149;">
      ⚠ For authorized security research only. Always operate within legal boundaries.
    </p>
  </footer>
</body>
</html>"""

        path = self.reports_dir / f"{self._base_filename()}.html"
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        return path

    def save(self, data: dict, ai_summary: Optional[str], fmt: str = "json"):
        paths = []
        if fmt in ("json", "both"):
            p = self._save_json(data, ai_summary)
            paths.append(p)
            console.print(f"[bold green]✓[/bold green] JSON report → [cyan]{p}[/cyan]")

        if fmt in ("html", "both"):
            p = self._save_html(data, ai_summary)
            paths.append(p)
            console.print(f"[bold green]✓[/bold green] HTML report → [cyan]{p}[/cyan]")

        return paths
